const mockProducts = [
    {
        _id: "mock1",
        name: "Classic White T-Shirt",
        description: "A comfortable classic white t-shirt made from 100% cotton.",
        price: 19.99,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Men",
        subCategory: "T-Shirts",
        stock: 100,
        sizes: ["S", "M", "L", "XL"],
        rating: 4.5,
        numReviews: 12,
        likes: [],
        comments: [],
        isFeatured: true,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock2",
        name: "Denim Jacket",
        description: "Stylish denim jacket for all seasons.",
        price: 49.99,
        image: "https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Men",
        subCategory: "Jackets",
        stock: 50,
        sizes: ["M", "L", "XL"],
        rating: 4.8,
        numReviews: 8,
        likes: [],
        comments: [],
        isFeatured: true,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock3",
        name: "Running Shoes",
        description: "Lightweight running shoes for optimal performance.",
        price: 89.99,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Men",
        subCategory: "Shoes",
        stock: 30,
        sizes: ["8", "9", "10", "11"],
        rating: 4.7,
        numReviews: 25,
        likes: [],
        comments: [],
        isFeatured: false,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock4",
        name: "Summer Floral Dress",
        description: "Beautiful floral dress perfect for summer days.",
        price: 39.99,
        image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Women",
        subCategory: "Dresses",
        stock: 45,
        sizes: ["XS", "S", "M", "L"],
        rating: 4.9,
        numReviews: 32,
        likes: [],
        comments: [],
        isFeatured: true,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock5",
        name: "Leather Handbag",
        description: "Premium leather handbag with spacious compartments.",
        price: 129.99,
        image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Women",
        subCategory: "Accessories",
        stock: 15,
        sizes: [],
        rating: 4.6,
        numReviews: 18,
        likes: [],
        comments: [],
        isFeatured: true,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock6",
        name: "Slim Fit Jeans",
        description: "Dark wash slim fit jeans with stretch comfort.",
        price: 34.99,
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Women",
        subCategory: "Jeans",
        stock: 60,
        sizes: ["26", "28", "30", "32"],
        rating: 4.4,
        numReviews: 22,
        likes: [],
        comments: [],
        isFeatured: false,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock7",
        name: "Kids Printed Hoodie",
        description: "Warm and cozy hoodie with fun prints for kids.",
        price: 24.99,
        image: "https://images.unsplash.com/photo-1519238809107-742f630545b9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Kids",
        subCategory: "Hoodies",
        stock: 80,
        sizes: ["4T", "6T", "8T", "10T"],
        rating: 4.7,
        numReviews: 15,
        likes: [],
        comments: [],
        isFeatured: false,
        createdAt: new Date().toISOString()
    },
    {
        _id: "mock8",
        name: "Baby Onesie Set",
        description: "Pack of 3 soft cotton onesies for infants.",
        price: 15.99,
        image: "https://images.unsplash.com/photo-1522771930-78848d9293e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        mainCategory: "Kids",
        subCategory: "Infant",
        stock: 120,
        sizes: ["0-3M", "3-6M", "6-12M"],
        rating: 4.8,
        numReviews: 40,
        likes: [],
        comments: [],
        isFeatured: true,
        createdAt: new Date().toISOString()
    }
];

module.exports = mockProducts;
